<?php

namespace AppBundle\Repository;

/**
 * AdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvRepository extends \Doctrine\ORM\EntityRepository
{
}
