<?php

namespace AppBundle\Repository;

/**
 * ImageSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
